---
ansible_user: "{{ win_username }}"
ansible_host: localhost

ansible_connection: winrm
ansible_winrm_transport: ntlm
ansible_winrm_server_cert_validation: ignore
ansible_winrm_scheme: http
ansible_port: 5985